### ISSUE TITLE
Passing --ignore-checksums to builds

### ISSUE THREAD

**Issue by rmusick** [TheCakeIsNaOH/choco-remixer#15]
HI Quick question,
Is it possible to pass a --ignore-checksums to a build?  Adobe Reader for example, works fine if you do a choco install adobereader from the sources, but when I attempt to internalize it, I get this:
WARNING: Checksum of D:\Scratch\adobereader\2023.3.20244\tools\AcroRdrDCUpd2300320244_MUI.msp invalid, file removed.
Wanted d2c75ba11c9d0681b5a23a6ffff08a0cd8b2a76370f63e669637203889d7ca77 got
38DA8AC0A689BD28CEB37F3B7F74FB59653128ED547F3577EF512D74EF1AAF81CE6B290B236FAA58CEE9B342905A34053342F6265E09537A7E1894F
8C7A8E790
WARNING: adobereader 2023.3.20244 failed downloading or editing
WARNING: Error details:
Invalid checksum after download for
https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/2300320244/AcroRdrDCUpd2300320244_MUI.msp
                Throw "Invalid checksum after download for $url"

at Get-File, D:\choco-remixer\public\Get-File.ps1: line 56
at Get-FileWithCache, D:\choco-remixer\public\Get-FileWithCache.ps1: line 29
at Convert-adobereader, D:\choco-remixer\pkgs\PkgFunctions-webfile.ps1: line 37
at Invoke-InternalizeChocoPkg, D:\choco-remixer\public\Invoke-InternalizeChocoPkg.ps1: line 195
at <ScriptBlock>, <No file>: line 1

Thanks for your help.

**Comment by TheCakeIsNaOH** [comment]
Generally, a broken checksum is a warning that something is going wrong. In this case, the package changed, and now includes the 64 bit installer, which broke the checksum type in choco-remixer. I've fixed it, if you pull the latest commit, internalization should be working again. 

In cases that the package itself is broken, instead of choco-remixer being broken, that is something that should be investigated manually, and likely fixed by the maintainer of the package. Or in cases like googlechrome, with the always latest version url, the `.nuspec` version should be updated to reflect the current version when the checksum breaks, which requires manual internalization. 

I'm open to other suggestions, or further clarification if that does not answer your question fully.

**Comment by rmusick** [comment]
Thank you.  Makes perfect sense to me.  I'll get the update configs and apply them.
Thanks again.
