### ISSUE TITLE
Citrix and Google Drive

### ISSUE THREAD

**Issue by julianbrennum** [TheCakeIsNaOH/choco-remixer#4]
I'm trying to internalize Citrix Workspace and Google Drive.

When I try to internalize Citrix Workspace nothing happens, no error message or anything. While on Google Drive it says: 
_"WARNING: googledrive 57.0.5.0 is new, id unknown"_

I have no clue how to fix these, especially the Citrix Workspace nupgk.

Btw, thank you for creating this neat tool!

**Comment by TheCakeIsNaOH** [comment]
For Google Drive, that should be working, I added it a few days ago. I'd suggest pulling the latest commit and seeing if it works. If not, comment here and we can investigate further.

For citrix workspace, that is not a package I am familiar with and is not a supported package (yet). It should be giving you the same message about it being a new package ID, so I'm not sure why it is not.

I don't have time to add it right now, but if you comment the package ID (from the community repository), I should be able to add support for it before long.
Otherwise, there is information here about how to add support for a new package: https://github.com/TheCakeIsNaOH/choco-remixer/blob/master/ADDING_PACKAGES.md

**Comment by TheCakeIsNaOH** [comment]
@julianbrennum I've added both packages.
